<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[************************ Browser Session Started ************************]]>
    </line>
    <line>
      <![CDATA[************************ Application Started ************************]]>
    </line>
    <line>
      <![CDATA[************************ Browser Session End ************************]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-12T19:45:54 IST" name="Default suite" finished-at="2022-07-12T19:46:35 IST" duration-ms="41604">
    <groups>
    </groups>
    <test started-at="2022-07-12T19:45:54 IST" name="Default test" finished-at="2022-07-12T19:46:35 IST" duration-ms="41604">
      <class name="sef.compassion.testcases.new_user">
        <test-method is-config="true" signature="setupApplication(java.lang.String, java.lang.String)[pri:0, instance:sef.compassion.testcases.new_user@2f7298b]" started-at="2022-07-12T19:45:54 IST" name="setupApplication" finished-at="2022-07-12T19:46:16 IST" duration-ms="22475" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[GC_2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[G33con0404]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[************************ Browser Session Started ************************]]>
            </line>
            <line>
              <![CDATA[************************ Application Started ************************]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupApplication -->
        <test-method signature="test()[pri:0, instance:sef.compassion.testcases.new_user@2f7298b]" started-at="2022-07-12T19:46:16 IST" name="test" finished-at="2022-07-12T19:46:26 IST" duration-ms="10146" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 1 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at sef.compassion.testcases.new_user.test(new_user.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:sef.compassion.testcases.new_user@2f7298b]" started-at="2022-07-12T19:46:26 IST" name="closeApplication" finished-at="2022-07-12T19:46:35 IST" duration-ms="8803" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[************************ Browser Session End ************************]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- sef.compassion.testcases.new_user -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
